name: Build Binder Image

on:
  workflow_dispatch:  # Manual trigger, you can add other triggers if you want

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build repo2docker image
        uses: jupyterhub/repo2docker-action@v0.5.0
        with:
          imageName: ghcr.io/dream-gcm/workshop-notebooks-2025:binder-latest

      - name: Push image to GitHub Container Registry
        run: docker push ghcr.io/dream-gcm/workshop-notebooks-2025:binder-latest

