name: Prebuild Binder Image

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Cache Binder Image on mybinder.org
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Trigger Binder image build and cache
        uses: jupyterhub/repo2docker-action@master
        with:
          NO_PUSH: true
